export function requireNonEmpty(value: string, fieldName: string) {
  if (!value.trim()) {
    throw new Error(`${fieldName} is required`);
  }

  return value.trim();
}

export {
  buildMobileTechnicianReadinessPanel,
  getDemoWorkflowSteps,
} from "./demoReadiness";
export type {
  DemoWorkflowStep,
  MobileTechnicianReadinessInput,
  MobileTechnicianReadinessPanel,
} from "./demoReadiness";
export {
  getProductionSmokeChecklist,
  getRemainingProductionReadinessActions,
} from "./productionReadiness";
export type {
  ProductionSmokeChecklistItem,
  RemainingProductionReadinessAction,
} from "./productionReadiness";

export {
  createAutomationRule,
  createNotificationEvent,
  createNotificationTemplate,
  archiveNotificationTemplate,
  buildAutomationSchedulerPlan,
  buildAutomationSchedulerPreview,
  buildNotificationDeliveryProviderPayload,
  dismissNotificationEvent,
  filterAutomationRules,
  filterNotificationEvents,
  filterNotificationEventsByRecipient,
  filterNotificationTemplates,
  getAutomationSummary,
  getAutomationSchedulerStatus,
  getNotificationDeliveryAttemptSummary,
  getNotificationDeliveryLabel,
  getNotificationDeliveryTriageSummary,
  getNotificationProviderStatus,
  getNotificationRecipientReadiness,
  getNotificationRecipientReadinessSummary,
  getNotificationRetryPolicyLabel,
  getNotificationRetryPolicyState,
  getPendingDeliverableNotifications,
  interpolateNotificationTemplateText,
  listAutomationRules,
  listAutomationSchedulerRuns,
  listNotificationEvents,
  listNotificationTemplates,
  markNotificationEventHandled,
  normalizeAutomationRuleInput,
  normalizeNotificationEventInput,
  normalizeNotificationTemplateInput,
  previewNotificationTemplateCopy,
  restoreNotificationTemplate,
  runAutomationSchedulerManual,
  runAutomationSchedulerForClient,
  sendNotificationEventDeliveries,
  sendNotificationEventDelivery,
  statusForAutomationRule,
  updateAutomationRuleStatus,
  updateAutomationRule,
  updateNotificationTemplate,
  validateAutomationRuleInput,
  validateNotificationEventId,
  validateNotificationEventInput,
  validateNotificationTemplateInput,
} from "./automation";
export type {
  AutomationSchedulerStatus,
  AutomationSchedulerPlan,
  AutomationSchedulerPreview,
  AutomationSchedulerPreviewItem,
  AutomationRuleStatusFilter,
  AutomationSummary,
  NotificationTemplatePreview,
  NotificationTemplatePreviewContext,
  NotificationTemplateVariable,
  NotificationDeliveryStatusFilter,
  NotificationDeliveryTriageSummary,
  NotificationDeliveryAttemptSummary,
  NotificationRetryPolicyState,
  NotificationRecipientReadinessFilter,
  NotificationRecipientReadiness,
  NotificationRecipientReadinessSummary,
  NotificationBulkDeliveryResult,
  NotificationEventStatusFilter,
  NotificationTemplateStatusFilter,
} from "./automation";
export {
  getCurrentAdminAuth,
  getCurrentTechnicianAuth,
  establishPasswordRecoverySession,
  requestPasswordReset,
  signInAdmin,
  signInTechnician,
  signOutAdmin,
  signOutTechnician,
  updateCurrentUserPassword,
  validateAdminAccess,
  validateAdminLoginInput,
  validateLoginInput,
  validatePasswordRecoverySessionInput,
  validatePasswordResetRequestInput,
  validatePasswordUpdateInput,
  validateTechnicianAccess,
  validateTechnicianLoginInput,
} from "./auth";
export type {
  LoginInput,
  PasswordRecoverySessionInput,
  PasswordResetRequestInput,
  PasswordUpdateInput,
  TechnicianLoginInput,
} from "./auth";
export {
  buildJobCloseoutReview,
  buildCustomerPortalCloseouts,
  createCustomerPortalAccessToken,
  filterCloseoutJobs,
  filterCustomerPortalCloseouts,
  getCustomerPortalAccessTokenLabel,
  getCustomerPortalAccessTokenState,
  getCloseoutCounts,
  listCustomerPortalAccessTokens,
  listCustomerPortalBilling,
  listCustomerPortalCloseouts,
  revokeCustomerPortalAccessToken,
  validateCustomerPortalAccessInput,
  validateCustomerPortalAccessToken,
  validateCustomerPortalAccessTokenId,
  validateCustomerPortalCustomerId,
} from "./closeouts";
export type { CloseoutCounts, CloseoutStatusFilter } from "./closeouts";
export {
  archiveCustomer,
  createCustomer,
  filterCustomers,
  listCustomers,
  normalizeCustomerInput,
  updateCustomer,
  validateCustomerInput,
} from "./customers";
export {
  assignJobTechnician,
  buildMobileDailyJobs,
  buildDispatchWeek,
  cancelJob,
  changeJobStatus,
  createJob,
  filterAssignedTechnicianJobs,
  filterJobs,
  getDispatchWeekStart,
  getRelativeDispatchWeek,
  jobToInput,
  listAssignedTechnicianJobs,
  listCustomerPortalJobs,
  listJobs,
  listTechnicians,
  normalizeJobInput,
  updateJob,
  validateJobInput,
} from "./jobs";
export {
  getTechnicianLabel,
  inviteTechnician,
  listTechnicianDirectory,
  normalizeTechnicianInviteInput,
  validateTechnicianInviteInput,
} from "./technicians";
export {
  archiveChemicalInventory,
  createChemicalInventory,
  createChemicalLog,
  createChemicalLogForClient,
  filterChemicalInventory,
  getInventorySummary,
  listChemicalInventory,
  listChemicalInventoryForClient,
  listJobChemicalLogs,
  listJobChemicalLogsForClient,
  listChemicalLogs,
  listChemicalLogsForClient,
  normalizeChemicalInventoryInput,
  normalizeChemicalLogInput,
  updateChemicalInventory,
  validateChemicalInventoryInput,
  validateChemicalLogInput,
} from "./inventory";
export {
  clearSyncedQueueItems,
  createOfflineQueueItem,
  getOfflineQueueSummary,
  markQueueItemFailed,
  markQueueItemRetrying,
  markQueueItemSynced,
  validateOfflineQueueInput,
} from "./offlineQueue";
export type { OfflineQueueSummary } from "./offlineQueue";
export {
  createFormDraft,
  createJobFormSubmission,
  defaultTreatmentFormTemplate,
  formDraftToSubmissionInput,
  listActiveFormTemplates,
  listCustomerPortalFormSubmissions,
  listJobFormSubmissions,
  normalizeFormSubmissionInput,
  updateFormDraftValue,
  validateFormSubmissionInput,
  validateFormTemplate,
} from "./forms";
export {
  buildJobGeofenceCheck,
  calculateDistanceMeters,
  createJobGeofenceEventQueuePayload,
  DEFAULT_GEOFENCE_RADIUS_METERS,
  normalizeJobGeofenceEventInput,
  validateJobGeofenceEventInput,
} from "./geofencing";
export type { GeoPoint, JobGeofenceCheck } from "./geofencing";
export {
  buildJobPhotoStoragePath,
  buildJobSignatureStoragePath,
  createJobSignatureCaptureQueuePayload,
  createJobPhotoUploadQueuePayload,
  JOB_MEDIA_BUCKET,
  listCustomerPortalMedia,
  listJobMedia,
  validateJobSignatureCaptureQueuePayload,
  validateJobPhotoUploadQueuePayload,
} from "./media";
export {
  buildInvoiceInputFromJob,
  buildCustomerPortalInvoices,
  createInvoice,
  createInvoicePaymentLink,
  filterCustomerPortalInvoices,
  filterInvoices,
  getCustomerPortalInvoiceStatusLabel,
  getInvoiceBalanceCents,
  getInvoiceInputTotalCents,
  getInvoiceJobIds,
  getInvoiceSummary,
  listInvoices,
  markInvoicePaid,
  normalizeInvoiceInput,
  normalizeInvoiceLineItemInput,
  validateInvoiceInput,
  voidInvoice,
} from "./payments";
export type {
  CustomerPortalInvoiceStatusFilter,
  InvoiceStatusFilter,
  InvoiceSummary,
} from "./payments";
export {
  hasReadyChemicalLogQueueItems,
  hasReadyFormSubmissionQueueItems,
  hasReadyGeofenceEventQueueItems,
  hasReadyJobStatusUpdateQueueItems,
  hasReadyOfflineQueueItems,
  hasReadyPhotoUploadQueueItems,
  hasReadySignatureCaptureQueueItems,
  isReadyChemicalLogQueueItem,
  isReadyFormSubmissionQueueItem,
  isReadyGeofenceEventQueueItem,
  isReadyJobStatusUpdateQueueItem,
  isReadyPhotoUploadQueueItem,
  isReadySignatureCaptureQueueItem,
  normalizeChemicalLogQueuePayload,
  normalizeFormSubmissionQueuePayload,
  normalizeJobGeofenceEventQueuePayload,
  normalizeJobPhotoUploadQueuePayload,
  normalizeJobSignatureCaptureQueuePayload,
  normalizeJobStatusUpdateQueuePayload,
  processChemicalLogQueueItem,
  processFormSubmissionQueueItem,
  processFormSubmissionQueueItems,
  processGeofenceEventQueueItem,
  processJobStatusUpdateQueueItem,
  processOfflineQueueItem,
  processOfflineQueueItems,
  processPhotoUploadQueueItem,
  processSignatureCaptureQueueItem,
} from "./offlineSync";
export type { QueueProcessResult, QueueProcessSummary } from "./offlineSync";
