export function requireNonEmpty(value: string, fieldName: string) {
  if (!value.trim()) {
    throw new Error(`${fieldName} is required`);
  }

  return value.trim();
}

export {
  buildMobileJobWorkPlan,
  buildMobileTechnicianReadinessPanel,
  getMobileCompletionReadinessGuard,
  getDemoWorkflowSteps,
} from "./demoReadiness";
export type {
  DemoWorkflowStep,
  MobileCompletionReadinessGuard,
  MobileJobWorkPlanItem,
  MobileJobWorkPlanState,
  MobileTechnicianReadinessInput,
  MobileTechnicianReadinessPanel,
} from "./demoReadiness";
export { buildHomeCommandCenterState } from "./homeCommandCenter";
export type {
  HomeCommandCenterAlert,
  HomeCommandCenterInput,
  HomeCommandCenterKpi,
  HomeCommandCenterKpiId,
  HomeLaunchReadinessId,
  HomeLaunchReadinessItem,
  HomeCommandCenterNextAction,
  HomeCommandCenterScheduleItem,
  HomeCommandCenterSeverity,
  HomeCommandCenterState,
  HomeSmokeChecklistItem,
} from "./homeCommandCenter";
export {
  DEMO_SEED_CONFIRMATION,
  DEMO_SEED_ADMIN_EMAIL,
  DEMO_SEED_ADMIN_PASSWORD,
  DEMO_SEED_MARKER,
  buildDemoSeedRuntimeStatus,
  buildDemoSeedPlan,
  getDemoSeedPlanSummary,
  validateDemoSeedGuardrails,
} from "./demoSeedData";
export type {
  DemoSeedAdminUser,
  DemoSeedChemicalLog,
  DemoSeedCustomer,
  DemoSeedFormSubmission,
  DemoSeedGuardrailInput,
  DemoSeedGuardrailResult,
  DemoSeedInventoryItem,
  DemoSeedInvoice,
  DemoSeedInvoiceLineItem,
  DemoSeedJob,
  DemoSeedPayment,
  DemoSeedPlan,
  DemoSeedRuntimeStatusInput,
  DemoSeedTable,
  DemoSeedTarget,
  DemoSeedTechnician,
} from "./demoSeedData";
export {
  buildDemoWorkflowFixtures,
  shouldUseLocalDemoFixtures,
} from "./demoWorkflowFixtures";
export type {
  DemoWorkflowFixtureEnv,
  DemoWorkflowFixtures,
} from "./demoWorkflowFixtures";
export { buildDemoSmokePreflight } from "./demoSmokePreflight";
export type {
  DemoSmokeEnv,
  DemoSmokeEnvName,
  DemoSmokePreflightCommand,
  DemoSmokePreflightInput,
  DemoSmokePreflightResult,
  DemoSmokePreflightState,
} from "./demoSmokePreflight";
export {
  getProductionSmokeChecklist,
  getRemainingProductionReadinessActions,
} from "./productionReadiness";
export type {
  ProductionSmokeChecklistItem,
  RemainingProductionReadinessAction,
} from "./productionReadiness";

export {
  createAutomationRule,
  createNotificationEvent,
  createNotificationTemplate,
  archiveNotificationTemplate,
  buildAutomationSchedulerPlan,
  buildAutomationSchedulerPreview,
  buildNotificationDeliveryProviderPayload,
  dismissNotificationEvent,
  filterAutomationRules,
  filterNotificationEvents,
  filterNotificationEventsByRecipient,
  filterNotificationTemplates,
  getAutomationSummary,
  getAutomationSchedulerStatus,
  getNotificationDeliveryAttemptSummary,
  getNotificationDeliveryLabel,
  getNotificationDeliveryTriageSummary,
  getNotificationProviderStatus,
  getNotificationRecipientReadiness,
  getNotificationRecipientReadinessSummary,
  getNotificationRetryPolicyLabel,
  getNotificationRetryPolicyState,
  getPendingDeliverableNotifications,
  interpolateNotificationTemplateText,
  listAutomationRules,
  listAutomationSchedulerRuns,
  listNotificationEvents,
  listNotificationTemplates,
  markNotificationEventHandled,
  normalizeAutomationRuleInput,
  normalizeNotificationEventInput,
  normalizeNotificationTemplateInput,
  previewNotificationTemplateCopy,
  restoreNotificationTemplate,
  runAutomationSchedulerManual,
  runAutomationSchedulerForClient,
  sendNotificationEventDeliveries,
  sendNotificationEventDelivery,
  statusForAutomationRule,
  updateAutomationRuleStatus,
  updateAutomationRule,
  updateNotificationTemplate,
  validateAutomationRuleInput,
  validateNotificationEventId,
  validateNotificationEventInput,
  validateNotificationTemplateInput,
} from "./automation";
export type {
  AutomationSchedulerStatus,
  AutomationSchedulerPlan,
  AutomationSchedulerPreview,
  AutomationSchedulerPreviewItem,
  AutomationRuleStatusFilter,
  AutomationSummary,
  NotificationTemplatePreview,
  NotificationTemplatePreviewContext,
  NotificationTemplateVariable,
  NotificationDeliveryStatusFilter,
  NotificationDeliveryTriageSummary,
  NotificationDeliveryAttemptSummary,
  NotificationRetryPolicyState,
  NotificationRecipientReadinessFilter,
  NotificationRecipientReadiness,
  NotificationRecipientReadinessSummary,
  NotificationBulkDeliveryResult,
  NotificationEventStatusFilter,
  NotificationTemplateStatusFilter,
} from "./automation";
export {
  getCurrentAdminAuth,
  getCurrentTechnicianAuth,
  establishPasswordRecoverySession,
  requestPasswordReset,
  signInAdmin,
  signInTechnician,
  signOutAdmin,
  signOutTechnician,
  updateCurrentUserPassword,
  validateAdminAccess,
  validateAdminProfile,
  validateAdminLoginInput,
  validateLoginInput,
  validatePasswordRecoverySessionInput,
  validatePasswordResetRequestInput,
  validatePasswordUpdateInput,
  validateTechnicianAccess,
  validateTechnicianLoginInput,
} from "./auth";
export type {
  LoginInput,
  PasswordRecoverySessionInput,
  PasswordResetRequestInput,
  PasswordUpdateInput,
  TechnicianLoginInput,
} from "./auth";
export {
  buildBillingQueue,
  buildJobCloseoutReview,
  buildCustomerPortalCloseouts,
  createCustomerPortalAccessToken,
  formatMissingCaptureList,
  filterCloseoutJobs,
  filterCustomerPortalCloseouts,
  getBillingQueueCounts,
  getBillingQueueItemSummary,
  getCloseoutReviewQueueFilters,
  getAdminCloseoutProofReview,
  getCloseoutProofHandoffSummary,
  getCustomerPortalAccessTokenLabel,
  getCustomerPortalAccessTokenEventLabel,
  getCustomerPortalAccessTokenReadiness,
  getCustomerPortalAccessTokenReadinessSummary,
  getCustomerPortalAccessTokenState,
  getCustomerPortalProofHandoff,
  getCustomerPortalProviderStatus,
  getCustomerPortalSendProviderStatusLabel,
  buildCustomerPortalTimeline,
  getCustomerPortalServiceSummary,
  getCloseoutCounts,
  getCloseoutReviewReadiness,
  getCloseoutReviewReadinessFromCounts,
  listCloseoutCaptureSummaries,
  listCustomerPortalAccessTokens,
  listCustomerPortalAccessTokenEvents,
  listCustomerPortalBilling,
  listCustomerPortalCloseouts,
  revokeCustomerPortalAccessToken,
  sendCustomerPortalAccessToken,
  validateCustomerPortalAccessInput,
  validateCustomerPortalAccessToken,
  validateCustomerPortalAccessTokenId,
  validateCustomerPortalCustomerId,
  validateCustomerPortalSendInput,
} from "./closeouts";
export type {
  BillingQueueCounts,
  BillingQueueGroup,
  BillingQueueItem,
  BillingQueueState,
  CloseoutCounts,
  CloseoutProofHandoffSummary,
  CloseoutReviewQueueFilter,
  CloseoutReviewQueueFilterId,
  CloseoutReviewReadiness,
  CloseoutStatusFilter,
  AdminCloseoutProofReview,
  CustomerPortalAccessTokenReadiness,
  CustomerPortalAccessTokenReadinessState,
  CustomerPortalAccessTokenReadinessSummary,
  CustomerPortalProofHandoff,
  CustomerPortalServiceSummary,
  CustomerPortalTimelineItem,
  CustomerPortalTimelineItemType,
} from "./closeouts";
export {
  archiveCustomer,
  createCustomer,
  filterCustomers,
  listCustomers,
  normalizeCustomerInput,
  updateCustomer,
  validateCustomerInput,
} from "./customers";
export {
  assignJobTechnician,
  buildDispatchStaticMapState,
  buildDispatchRouteExceptionSummary,
  buildDispatchRouteGroupSummaries,
  buildDispatchRouteIntelligence,
  buildDispatchRouteIntelligenceForDays,
  buildMobileDailyRouteTimeline,
  buildMobileDailyJobs,
  buildDispatchWeek,
  cancelJob,
  changeJobStatus,
  createJob,
  filterDispatchRouteStops,
  filterAssignedTechnicianJobs,
  filterJobs,
  getDispatchWeekStart,
  getRelativeDispatchWeek,
  jobToInput,
  listAssignedTechnicianJobs,
  listCustomerPortalJobs,
  listJobs,
  listTechnicians,
  normalizeJobInput,
  parseJobScheduleWallTime,
  updateJob,
  validateJobInput,
} from "./jobs";
export type {
  DispatchRouteEvidenceState,
  DispatchRouteExceptionSummary,
  DispatchRouteExceptionSummaryItem,
  DispatchRouteGroupDaySummary,
  DispatchRouteGroupSummary,
  DispatchRouteGroupSummaryOptions,
  DispatchRouteIntelligence,
  DispatchRouteIntelligenceSummary,
  DispatchRouteRiskState,
  DispatchRouteLocationState,
  DispatchRouteStop,
  DispatchRouteStopStatusState,
  DispatchRouteTriageFilter,
  DispatchStaticMapBounds,
  DispatchStaticMapPoint,
  DispatchStaticMapPointSource,
  DispatchStaticMapState,
  DispatchStaticMapStateOptions,
  DispatchStaticMapSummary,
  TechnicianFilter,
  MobileDailyRouteTimeline,
  MobileRouteTimelineNextAction,
  MobileRouteTimelineNextActionSeverity,
  MobileRouteTimelineJob,
  MobileRouteTimelineSummary,
} from "./jobs";
export {
  buildTechnicianRouteLoadSummaries,
  getTechnicianLabel,
  inviteTechnician,
  listTechnicianDirectory,
  normalizeTechnicianInviteInput,
  validateTechnicianInviteInput,
} from "./technicians";
export type {
  TechnicianRouteLoadSummary,
  TechnicianRouteStatus,
} from "./technicians";
export {
  archiveChemicalInventory,
  createChemicalInventory,
  createChemicalLog,
  createChemicalLogForClient,
  filterChemicalInventory,
  getInventorySummary,
  listChemicalInventory,
  listChemicalInventoryForClient,
  listJobChemicalLogs,
  listJobChemicalLogsForClient,
  listChemicalLogs,
  listChemicalLogsForClient,
  normalizeChemicalInventoryInput,
  normalizeChemicalLogInput,
  updateChemicalInventory,
  validateChemicalInventoryInput,
  validateChemicalLogInput,
} from "./inventory";
export {
  buildComplianceAdvisory,
  buildComplianceIngestionPlan,
  buildComplianceQueryText,
  buildComplianceSourceHash,
  chunkComplianceDocumentText,
  COMPLIANCE_RAG_MIGRATION_NAME,
  complianceSourceAnchors,
  getComplianceKnowledgeBaseReadiness,
  createComplianceAdvisoryAudit,
  getComplianceMultiUnitAuditSummary,
  getComplianceRuntimeStatus,
  getComplianceSchemaReadyReadiness,
  getComplianceSchemaUnavailableReadiness,
  getComplianceSourceFilters,
  listComplianceAdvisoryAudits,
  listComplianceChunks,
  listComplianceDocuments,
  listComplianceSources,
  searchComplianceChunks,
  validateComplianceAdvisoryRequest,
  validateComplianceChunkSearchInput,
  validateComplianceSourceManifestEntry,
  validateLocationUnitLabel,
} from "./compliance";
export type {
  ComplianceAdvisoryBuildInput,
  ComplianceChunkSearchInput,
  ComplianceChunkIngestionInput,
  ComplianceDocumentIngestionInput,
  ComplianceIngestionPlan,
  ComplianceKnowledgeBaseReadiness,
  ComplianceKnowledgeBaseReadinessStatus,
  ComplianceMultiUnitAuditSummary,
  ComplianceRuntimeEnv,
  ComplianceRuntimeStatus,
  ComplianceSetupReadiness,
  ComplianceSourceIngestionInput,
  ComplianceSourceManifestEntry,
  ComplianceWorkflowKnowledgeBaseReadiness,
} from "./compliance";
export {
  clearSyncedQueueItems,
  createOfflineQueueItem,
  getOfflineQueueJobTriage,
  getOfflineQueueItemLabel,
  getOfflineQueueSummary,
  markQueueItemFailed,
  markQueueItemRetrying,
  markQueueItemSynced,
  validateOfflineQueueInput,
} from "./offlineQueue";
export type {
  OfflineQueueJobTriage,
  OfflineQueueJobTriageState,
  OfflineQueueSummary,
} from "./offlineQueue";
export {
  createFormDraft,
  createJobFormSubmission,
  defaultTreatmentFormTemplate,
  formDraftToSubmissionInput,
  listActiveFormTemplates,
  listCustomerPortalFormSubmissions,
  listJobFormSubmissions,
  normalizeFormSubmissionInput,
  updateFormDraftValue,
  validateFormSubmissionInput,
  validateFormTemplate,
} from "./forms";
export {
  buildDispatchLocationEvidenceByJob,
  buildDispatchLocationMapUrl,
  buildJobGeofenceCheck,
  calculateDistanceMeters,
  createJobGeofenceEventQueuePayload,
  DEFAULT_GEOFENCE_RADIUS_METERS,
  listJobGeofenceEvents,
  normalizeJobGeofenceEventInput,
  validateJobGeofenceEventInput,
} from "./geofencing";
export type {
  DispatchLocationEvidence,
  DispatchLocationEvidenceByJob,
  DispatchLocationEvidenceEvent,
  DispatchLocationEvidenceRadiusState,
  DispatchLocationEvidenceState,
  GeoPoint,
  JobGeofenceCheck,
} from "./geofencing";
export {
  buildJobPhotoStoragePath,
  buildJobSignatureStoragePath,
  createJobSignatureCaptureQueuePayload,
  createJobPhotoUploadQueuePayload,
  JOB_MEDIA_BUCKET,
  listCustomerPortalMedia,
  listJobMedia,
  validateJobSignatureCaptureQueuePayload,
  validateJobPhotoUploadQueuePayload,
} from "./media";
export {
  buildInvoiceInputFromJob,
  buildCustomerPortalInvoices,
  createInvoice,
  createInvoicePaymentLink,
  filterCustomerPortalInvoices,
  filterInvoices,
  getBillingCloseoutHandoffSummary,
  getCustomerPortalInvoiceStatusLabel,
  getInvoiceBalanceCents,
  getInvoiceHandoffHref,
  getInvoiceInputTotalCents,
  getInvoiceJobIds,
  getInvoicePaidCents,
  getInvoiceReconciliation,
  getInvoiceReconciliationGuidance,
  getInvoiceReconciliationSummary,
  getInvoiceSummary,
  listInvoices,
  markInvoicePaid,
  normalizeInvoiceInput,
  normalizeInvoiceLineItemInput,
  validateInvoiceInput,
  voidInvoice,
} from "./payments";
export type {
  BillingCloseoutHandoffSummary,
  CustomerPortalInvoiceStatusFilter,
  InvoiceReconciliation,
  InvoiceReconciliationGuidance,
  InvoiceReconciliationStatus,
  InvoiceReconciliationSummary,
  InvoiceStatusFilter,
  InvoiceSummary,
} from "./payments";
export {
  buildBillingPortalNextActions,
  buildCustomerLedger,
  getCustomerPortalHandoffReview,
  getCustomerLedgerSummary,
} from "./customerLedger";
export type {
  BillingPortalNextAction,
  BillingPortalNextActionId,
  BillingPortalNextActionInput,
  CustomerPortalHandoffReview,
  CustomerPortalHandoffReviewInput,
  CustomerLedgerEntry,
  CustomerLedgerEntryType,
  CustomerLedgerInput,
  CustomerLedgerSummary,
} from "./customerLedger";
export {
  hasReadyChemicalLogQueueItems,
  hasReadyFormSubmissionQueueItems,
  hasReadyGeofenceEventQueueItems,
  hasReadyJobStatusUpdateQueueItems,
  hasReadyOfflineQueueItems,
  hasReadyPhotoUploadQueueItems,
  hasReadySignatureCaptureQueueItems,
  isReadyChemicalLogQueueItem,
  isReadyFormSubmissionQueueItem,
  isReadyGeofenceEventQueueItem,
  isReadyJobStatusUpdateQueueItem,
  isReadyPhotoUploadQueueItem,
  isReadySignatureCaptureQueueItem,
  normalizeChemicalLogQueuePayload,
  normalizeFormSubmissionQueuePayload,
  normalizeJobGeofenceEventQueuePayload,
  normalizeJobPhotoUploadQueuePayload,
  normalizeJobSignatureCaptureQueuePayload,
  normalizeJobStatusUpdateQueuePayload,
  processChemicalLogQueueItem,
  processFormSubmissionQueueItem,
  processFormSubmissionQueueItems,
  processGeofenceEventQueueItem,
  processJobStatusUpdateQueueItem,
  processOfflineQueueItem,
  processOfflineQueueItems,
  processPhotoUploadQueueItem,
  processSignatureCaptureQueueItem,
} from "./offlineSync";
export type { QueueProcessResult, QueueProcessSummary } from "./offlineSync";
